Add user, group, and timeout properties to osl_gitlfs resource
osuosl-cookbooks/osl-git pull request #17
Opened 2020-09-11 00:00 UTC by daviddjh

Changes being made for proj-lf:archive

2020-09-11 17:56 UTC, daviddjh commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix missing images for http://events17.linuxfoundation.org/events/kubecon-and-cloudnativecon-europe](https://trello.com/c/Z8YhtPRU/46-fix-missing-images-for-http-events17linuxfoundationorg-events-kubecon-and-cloudnativecon-europe)

2020-09-11 23:22 UTC, ramereth requested changes

2020-09-11 23:22 UTC, ramereth commented on resources/osl_gitlfs.rb
> +property :timeout, Integer
These really should have some default values I think.

2020-09-14 19:11 UTC, ramereth approved these changes
Please do a minor bump.

2020-09-14 19:12 UTC, daviddjh commented
!bump minor *

2020-09-14 19:13 UTC, merged

2020-09-14 19:13 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.5.0.  Have a nice day!